version: '3.8'                                    # Указание версии
services:                                         # Описание сервисов, с которыми мы будем работать
  mock-server:                                    # Сервис Prism
    image: stoplight/prism:4                      # Какой образ необходимо взять для сервиса
    volumes:                                      # Подключение томов
      - ./openAPI_example.yaml:/openapi.yaml      # Подключаем openAPI спецификацию, не забудьте изменить на путь к своему файлу
    command: mock -h 0.0.0.0 /openapi.yaml        # Команда, выполняемая при запуске контейнера
    environment:                                  # переменные окружение
      PRISM_DYNAMIC: "true"                       # Делаем возможным динамическую генерацию ответов
    ports:                                        # Проброс портов
      - "4010:4010"                               # Вызываем на порту 4010
  fastapi-app:                                    # Сервис fastAPI
    build: .                                      # Говорим, что образ нужно собрать из текущего контекста и Докерфайла в указанной директории
    ports:
      - "8000:8000"                               # Приложение будет работать на этом порту, документация на localhost:8000/docs
    volumes:
      - ./app:/app/app                            # для локальной разработки, чтобы видеть изменения без пересборки