version: '3.8'                                    # Указание версии
services:                                         # Описание сервисов, с которыми мы будем работать
  mock-server:                                    # Сервис Prism
    image: stoplight/prism:4                      # Какой образ необходимо взять для сервиса
    volumes:                                      # Подключение томов
      - ./openAPI_example.yaml:/openapi.yaml      # Подключаем openAPI спецификацию, не забудьте изменить на путь к своему файлу
    command: mock -h 0.0.0.0 /openapi.yaml        # Команда, выполняемая при запуске контейнера
    environment:                                  # переменные окружение
      PRISM_DYNAMIC: "true"                       # Делаем возможным динамическую генерацию ответов
    ports:                                        # Проброс портов
      - "4010:4010"                               # Вызываем на порту 4010